# Generated by Django 5.1.5 on 2025-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='type',
        ),
        migrations.AddField(
            model_name='weapons',
            name='item_category',
            field=models.CharField(blank=True, choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], default='other', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='item_type',
            field=models.CharField(choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], default='universal', max_length=10),
        ),
    ]
