# Generated by Django 5.1.5 on 2025-09-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_remove_weapons_type_weapons_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='armor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='dex_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='int_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='luk_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='max_dmg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='min_dmg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapons',
            name='prum_dmg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_1_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_1_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_2_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_2_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_3_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_3_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_4_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slot_4_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='str_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='vit_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='img_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='item_category',
            field=models.CharField(choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='level_required',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='level_stop',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
