# Generated by Django 5.1.5 on 2025-09-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0003_weapons_armor_weapons_dex_bonus_weapons_int_bonus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapons',
            new_name='Items',
        ),
    ]
