# Generated by Django 5.1.5 on 2025-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_rename_weapons_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_id', models.IntegerField(max_length=100, unique=True, verbose_name='Bonus ID')),
                ('bonus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bonus_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bonus_min_value', models.IntegerField(blank=True, default=0, null=True)),
                ('bonus_max_value', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
