# Generated by Django 5.1.5 on 2025-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0005_items_bonus_alter_items_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_bonus',
            name='bonus_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus ID'),
        ),
        migrations.AlterField(
            model_name='items_bonus',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('def', 'defenzivní'), ('off', 'ofenzivní'), ('other', 'ostatní')], max_length=20, null=True),
        ),
    ]
