# Generated by Django 5.1.5 on 2025-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0006_alter_items_bonus_bonus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
