# Generated by Django 5.1.5 on 2025-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0007_alter_items_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_bonus',
            name='flat_or_procent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
