# Generated by Django 5.1.5 on 2025-09-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0008_items_bonus_flat_or_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_bonus',
            name='flat_or_procent',
            field=models.CharField(blank=True, default='%', max_length=10, null=True),
        ),
    ]
