# Generated by Django 5.1.5 on 2025-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0009_alter_items_bonus_flat_or_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sell_price',
            field=models.FloatField(default=0, verbose_name='Prodejní cena'),
        ),
    ]
