# Generated by Django 5.1.5 on 2025-09-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0010_items_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='img_init',
        ),
    ]
