# Generated by Django 5.1.5 on 2025-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0011_remove_items_img_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='weapons_images/'),
        ),
    ]
