# Generated by Django 5.1.5 on 2025-09-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, default=1)),
                ('item_type', models.CharField(choices=[('weapon', 'Zbraň'), ('armor', 'Brnění')], max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('item_price', models.PositiveIntegerField(blank=True, default=1)),
                ('item_description', models.TextField(blank=True)),
                ('item_level_required', models.PositiveIntegerField(blank=True, default=1)),
                ('item_level_stop', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_type', models.CharField(blank=True, default=1, max_length=20)),
                ('weapon_base_damage', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_min_damage', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_max_damage', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_slots', models.PositiveIntegerField(blank=True, default=1)),
            ],
        ),
    ]
