# Generated by Django 5.1.5 on 2025-09-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopOffer',
        ),
    ]
