# Generated by Django 5.1.5 on 2025-09-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob_id', models.IntegerField(unique=True, verbose_name='ID Monstra')),
                ('dificulty_koeficient', models.IntegerField(blank=True, default=1, null=True, verbose_name='Obtížnost')),
                ('lvl', models.IntegerField(blank=True, default=1, null=True, verbose_name='Úroveň')),
                ('hp', models.IntegerField(blank=True, default=1, null=True, verbose_name='Životy')),
                ('str', models.IntegerField(blank=True, default=1, null=True, verbose_name='Síla')),
                ('dex', models.IntegerField(blank=True, default=1, null=True, verbose_name='Obratnost')),
                ('int', models.IntegerField(blank=True, default=1, null=True, verbose_name='Inteligence')),
                ('vit', models.IntegerField(blank=True, default=1, null=True, verbose_name='Vitalita')),
                ('luck', models.IntegerField(blank=True, default=1, null=True, verbose_name='Štěstí')),
                ('dmg_atr', models.CharField(choices=[('strength', 'Síla'), ('dexterity', 'Obratnost'), ('intelligence', 'Inteligence'), ('luck', 'Štěstí'), ('vitality', 'Vitalita'), ('none', 'Žádný')], default='none', max_length=100)),
                ('magic_resist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Magická odolnost')),
                ('light_resist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Lehká odolnost')),
                ('heavy_resist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Těžká odolnost')),
                ('otrava_resist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Otrava odolnost')),
                ('bezvedomi_resist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Bezvědomí odolnost')),
                ('poskozeni_schopnosti', models.IntegerField(blank=True, default=0, null=True, verbose_name='Poškození schopností')),
                ('poskozeni_utokem', models.IntegerField(blank=True, default=0, null=True, verbose_name='Poškození útokem')),
                ('sance_na_otravu', models.IntegerField(blank=True, default=0, null=True, verbose_name='Šance na otravu')),
                ('sance_na_bezvedomi', models.IntegerField(blank=True, default=0, null=True, verbose_name='Šance na bezvědomí')),
                ('sance_na_kriticky_utok', models.IntegerField(blank=True, default=0, null=True, verbose_name='Šance na kritický útok')),
                ('kriticke_poskozeni', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kritické poškození')),
                ('armor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Brnění')),
                ('min_dmg', models.IntegerField(blank=True, default=1, null=True, verbose_name='Minimální poškození')),
                ('max_dmg', models.IntegerField(blank=True, default=1, null=True, verbose_name='Maximální poškození')),
            ],
        ),
    ]
