# Generated by Django 5.1.5 on 2025-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobs',
            name='armor',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Brnění'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='bezvedomi_resist',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bezvědomí odolnost'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='dex',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Obratnost'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='heavy_resist',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Těžká odolnost'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='hp',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Životy'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='int',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Inteligence'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='kriticke_poskozeni',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kritické poškození'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='light_resist',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Lehká odolnost'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='luck',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Štěstí'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='magic_resist',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Magická odolnost'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='max_dmg',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Maximální poškození'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='min_dmg',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Minimální poškození'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='otrava_resist',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Otrava odolnost'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='poskozeni_schopnosti',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Poškození schopností'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='poskozeni_utokem',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Poškození útokem'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='sance_na_bezvedomi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Šance na bezvědomí'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='sance_na_kriticky_utok',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Šance na kritický útok'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='sance_na_otravu',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Šance na otravu'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='str',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Síla'),
        ),
        migrations.AlterField(
            model_name='mobs',
            name='vit',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Vitalita'),
        ),
    ]
