# Generated by Django 5.1.5 on 2025-09-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvmapp', '0002_alter_mobs_armor_alter_mobs_bezvedomi_resist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobs',
            new_name='Mobs_random',
        ),
    ]
