# Generated by Django 5.1.5 on 2025-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvmapp', '0003_rename_mobs_mobs_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobs_dungeons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.IntegerField(blank=True, null=True, verbose_name='Název Dungeonu')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Patro Dungeonu')),
                ('name', models.CharField(max_length=100)),
                ('mob_id', models.IntegerField(unique=True, verbose_name='ID Monstra')),
                ('img', models.ImageField(blank=True, null=True, upload_to='mobs_images/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('dificulty_koeficient', models.IntegerField(blank=True, default=1, null=True, verbose_name='Obtížnost')),
                ('lvl', models.IntegerField(blank=True, default=1, null=True, verbose_name='Úroveň')),
                ('gold_loot_bonus', models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus ke zlatým')),
                ('xp_loot_bonus', models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k XP')),
                ('items_loot_bonus', models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k předmětům')),
                ('hp', models.FloatField(blank=True, default=1, null=True, verbose_name='Životy')),
                ('str', models.FloatField(blank=True, default=1, null=True, verbose_name='Síla')),
                ('dex', models.FloatField(blank=True, default=1, null=True, verbose_name='Obratnost')),
                ('int', models.FloatField(blank=True, default=1, null=True, verbose_name='Inteligence')),
                ('vit', models.FloatField(blank=True, default=1, null=True, verbose_name='Vitalita')),
                ('luck', models.FloatField(blank=True, default=1, null=True, verbose_name='Štěstí')),
                ('dmg_atr', models.CharField(choices=[('strength', 'Síla'), ('dexterity', 'Obratnost'), ('intelligence', 'Inteligence'), ('luck', 'Štěstí'), ('vitality', 'Vitalita'), ('none', 'Žádný')], default='none', max_length=100)),
                ('magic_resist', models.FloatField(blank=True, default=0, null=True, verbose_name='Magická odolnost')),
                ('light_resist', models.FloatField(blank=True, default=0, null=True, verbose_name='Lehká odolnost')),
                ('heavy_resist', models.FloatField(blank=True, default=0, null=True, verbose_name='Těžká odolnost')),
                ('otrava_resist', models.FloatField(blank=True, default=0, null=True, verbose_name='Otrava odolnost')),
                ('bezvedomi_resist', models.FloatField(blank=True, default=0, null=True, verbose_name='Bezvědomí odolnost')),
                ('poskozeni_schopnosti', models.FloatField(blank=True, default=0, null=True, verbose_name='Poškození schopností')),
                ('poskozeni_utokem', models.FloatField(blank=True, default=0, null=True, verbose_name='Poškození útokem')),
                ('sance_na_otravu', models.FloatField(blank=True, default=0, null=True, verbose_name='Šance na otravu')),
                ('sance_na_bezvedomi', models.FloatField(blank=True, default=0, null=True, verbose_name='Šance na bezvědomí')),
                ('sance_na_kriticky_utok', models.FloatField(blank=True, default=0, null=True, verbose_name='Šance na kritický útok')),
                ('kriticke_poskozeni', models.FloatField(blank=True, default=0, null=True, verbose_name='Kritické poškození')),
                ('armor', models.FloatField(blank=True, default=0, null=True, verbose_name='Brnění')),
                ('min_dmg', models.FloatField(blank=True, default=1, null=True, verbose_name='Minimální poškození')),
                ('max_dmg', models.FloatField(blank=True, default=1, null=True, verbose_name='Maximální poškození')),
            ],
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='bezvedomi_resist',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='dex',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='dificulty_koeficient',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='dmg_atr',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='heavy_resist',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='int',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='kriticke_poskozeni',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='light_resist',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='lvl',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='magic_resist',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='max_dmg',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='min_dmg',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='otrava_resist',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='poskozeni_schopnosti',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='poskozeni_utokem',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='sance_na_bezvedomi',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='sance_na_kriticky_utok',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='sance_na_otravu',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='str',
        ),
        migrations.RemoveField(
            model_name='mobs_random',
            name='vit',
        ),
        migrations.AddField(
            model_name='mobs_random',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='mobs_random',
            name='gold_loot_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus ke zlatým'),
        ),
        migrations.AddField(
            model_name='mobs_random',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mobs_images/'),
        ),
        migrations.AddField(
            model_name='mobs_random',
            name='items_loot_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k předmětům'),
        ),
        migrations.AddField(
            model_name='mobs_random',
            name='locations',
            field=models.TextField(blank=True, null=True, verbose_name='Lokace'),
        ),
        migrations.AddField(
            model_name='mobs_random',
            name='xp_loot_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k XP'),
        ),
    ]
