# Generated by Django 5.1.5 on 2025-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvmapp', '0004_mobs_dungeons_remove_mobs_random_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobs_dungeons',
            name='dungeon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Číslo Dungeonu'),
        ),
    ]
