# Generated by Django 5.1.5 on 2025-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xp_lvl',
            name='povolani',
        ),
        migrations.RemoveField(
            model_name='xp_lvl',
            name='rasa',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='povolani',
            field=models.CharField(blank=True, choices=[('choice:', 'Vyber:'), ('ranger', 'Hraničář'), ('monk', 'Mnich'), ('warrior', 'Válečník'), ('paladin', 'Paladin'), ('mage', 'Mág'), ('rogue', 'Roguna'), ('necromancer', 'Nekromant'), ('berserker', 'Ničitel'), ('druid', 'Druid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, choices=[('Choice:', 'Vyber:'), ('human', 'Člověk'), ('elf', 'Elf'), ('dwarf', 'Trpaslík'), ('ork', 'ork'), ('gnóm', 'Gnóm'), ('shadow', 'Stín')], max_length=20, null=True),
        ),
    ]
