# Generated by Django 5.1.5 on 2025-09-01 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0002_remove_xp_lvl_povolani_remove_xp_lvl_rasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributs',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character_bonus',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_bonus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='economy',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eqp',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inv',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xp_lvl',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_lvl', to=settings.AUTH_USER_MODEL),
        ),
    ]
