# Generated by Django 5.1.5 on 2025-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0003_alter_atributs_hrac_alter_character_bonus_hrac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributs',
            name='dmg_atribut',
            field=models.CharField(blank=True, choices=[('strength', 'Síla'), ('dexterity', 'Obratnost'), ('intelligence', 'Inteligence'), ('charisma', 'Charisma'), ('luck', 'Štěstí'), ('vitality', 'Vitalita')], max_length=20, null=True),
        ),
    ]
