# Generated by Django 5.1.5 on 2025-09-02 06:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0004_alter_atributs_dmg_atribut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='last_gold_collection',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
