# Generated by Django 5.1.5 on 2025-09-02 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0005_alter_economy_last_gold_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='last_gold_collection',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='ShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, default=1)),
                ('item_type', models.CharField(choices=[('weapon', 'Zbraň'), ('armor', 'Brnění')], max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('item_price', models.PositiveIntegerField(blank=True, default=1)),
                ('item_description', models.TextField(blank=True)),
                ('item_level_required', models.PositiveIntegerField(blank=True, default=1)),
                ('item_level_stop', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_type', models.CharField(blank=True, default=1, max_length=20)),
                ('weapon_base_damage', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_min_damage', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_max_damage', models.PositiveIntegerField(blank=True, default=1)),
                ('weapon_slots', models.PositiveIntegerField(blank=True, default=1)),
                ('hrac', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
