# Generated by Django 5.1.5 on 2025-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0006_alter_economy_last_gold_collection_shopoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopoffer',
            old_name='weapon_base_damage',
            new_name='item_base_damage',
        ),
        migrations.RenameField(
            model_name='shopoffer',
            old_name='weapon_max_damage',
            new_name='item_max_damage',
        ),
        migrations.RenameField(
            model_name='shopoffer',
            old_name='weapon_min_damage',
            new_name='item_min_damage',
        ),
        migrations.RenameField(
            model_name='shopoffer',
            old_name='weapon_slots',
            new_name='item_slots',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='weapon_type',
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_type',
            field=models.CharField(blank=True, default=1, max_length=20),
        ),
    ]
