# Generated by Django 5.1.5 on 2025-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0007_rename_weapon_base_damage_shopoffer_item_base_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoffer',
            name='item_weapon_type',
            field=models.CharField(blank=True, default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Zbraň'), ('armor', 'Brnění')], max_length=20),
        ),
    ]
