# Generated by Django 5.1.5 on 2025-09-02 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0008_shopoffer_item_weapon_type_alter_shopoffer_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xp_lvl',
            name='hrac',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_lvl', to=settings.AUTH_USER_MODEL),
        ),
    ]
