# Generated by Django 5.1.5 on 2025-09-02 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0009_alter_xp_lvl_hrac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributs',
            name='hrac',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='economy',
            name='hrac',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy', to=settings.AUTH_USER_MODEL),
        ),
    ]
