# Generated by Django 5.1.5 on 2025-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0011_inv_item_base_damage_inv_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqp',
            name='item_base_damage',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_level_required',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_level_stop',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_max_damage',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_min_damage',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_price',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_slots',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_type',
            field=models.CharField(blank=True, choices=[('weapon', 'Zbraň'), ('armor', 'Brnění')], max_length=20),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_weapon_type',
            field=models.CharField(blank=True, default=1, max_length=20),
        ),
    ]
