# Generated by Django 5.1.5 on 2025-09-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0012_eqp_item_base_damage_eqp_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='steps',
        ),
    ]
