# Generated by Django 5.1.5 on 2025-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0013_remove_playerinfo_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='xp_lvl',
            name='xp_nasetreno',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='XP nasetřeno'),
        ),
        migrations.AddField(
            model_name='xp_lvl',
            name='xp_to_next_lvl',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='XP do další úrovně'),
        ),
    ]
