# Generated by Django 5.1.5 on 2025-09-04 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0014_xp_lvl_xp_nasetreno_xp_lvl_xp_to_next_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='xp_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_record', models.IntegerField(blank=True, default=0, null=True, verbose_name='Získané XP')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hrac', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
