# Generated by Django 5.1.5 on 2025-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0015_xp_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='dungeon_token',
            field=models.IntegerField(default=0, verbose_name='Počet DUNGEON TOKENŮ'),
        ),
    ]
