# Generated by Django 5.1.5 on 2025-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0016_economy_dungeon_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xp_lvl',
            name='lvl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Úroveň'),
        ),
        migrations.AlterField(
            model_name='xp_lvl',
            name='xp_to_next_lvl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='XP do další úrovně'),
        ),
    ]
