# Generated by Django 5.1.5 on 2025-09-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0017_alter_xp_lvl_lvl_alter_xp_lvl_xp_to_next_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xp_lvl',
            name='lvl',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Úroveň'),
        ),
        migrations.AlterField(
            model_name='xp_lvl',
            name='xp_to_next_lvl',
            field=models.IntegerField(blank=True, default=50, null=True, verbose_name='XP do další úrovně'),
        ),
    ]
