# Generated by Django 5.1.5 on 2025-09-05 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0018_alter_xp_lvl_lvl_alter_xp_lvl_xp_to_next_lvl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economy',
            name='gold_growth_coefficient',
        ),
        migrations.RemoveField(
            model_name='economy',
            name='last_gold_collection',
        ),
        migrations.RemoveField(
            model_name='economy',
            name='rohlik',
        ),
        migrations.CreateModel(
            name='Economy_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_change', models.IntegerField(blank=True, default=0, null=True, verbose_name='Změna GOLDŮ')),
                ('dungeon_token_change', models.IntegerField(blank=True, default=0, null=True, verbose_name='Změna DUNGEON TOKENŮ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hrac', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
