# Generated by Django 5.1.5 on 2025-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0019_remove_economy_gold_growth_coefficient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributs',
            old_name='hp_bonus',
            new_name='hp_base',
        ),
        migrations.RenameField(
            model_name='atributs',
            old_name='HP',
            new_name='suma_hp',
        ),
        migrations.AddField(
            model_name='atributs',
            name='hp_plus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='plus k životům'),
        ),
    ]
