# Generated by Django 5.1.5 on 2025-09-05 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0020_rename_hp_bonus_atributs_hp_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributs',
            name='hp_base',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='Bonus k životům'),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='hrac',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='suma_hp',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Počet životů'),
        ),
    ]
