# Generated by Django 5.1.5 on 2025-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0021_alter_atributs_hp_base_alter_atributs_hrac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributs',
            name='hp_bonus_procenta',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (%)'),
        ),
    ]
