# Generated by Django 5.1.5 on 2025-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0022_atributs_hp_bonus_procenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributs',
            name='charisma_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení charismatu'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='charisma_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k charismatu (předměty)'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='dexterity_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení obratnosti'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='dexterity_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k obratnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='hp_items',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (předměty)'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='intelligence_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení inteligence'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='intelligence_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k inteligenci (předměty)'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='luck_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení zručnosti'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='luck_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k zručnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='strength_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení síly'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='strength_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k síle (předměty)'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='vitality_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení vitality'),
        ),
        migrations.AddField(
            model_name='atributs',
            name='vitality_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k vitalitě (předměty)'),
        ),
    ]
