# Generated by Django 5.1.5 on 2025-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0023_atributs_charisma_cena_atributs_charisma_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='poz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
