# Generated by Django 5.1.5 on 2025-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0024_playerinfo_poz'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributs',
            name='hp_rasa',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Životy z rasy'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='povolani',
            field=models.CharField(blank=True, choices=[('ranger', 'Hraničář'), ('monk', 'Mnich'), ('warrior', 'Válečník'), ('paladin', 'Paladin'), ('mage', 'Mág'), ('rogue', 'Roguna'), ('necromancer', 'Nekromant'), ('berserker', 'Ničitel'), ('druid', 'Druid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, choices=[('human', 'Člověk'), ('elf', 'Elf'), ('dwarf', 'Trpaslík'), ('ork', 'ork'), ('gnóm', 'Gnóm'), ('shadow', 'Stín')], max_length=20, null=True),
        ),
    ]
