# Generated by Django 5.1.5 on 2025-09-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0025_atributs_hp_rasa_alter_playerinfo_povolani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributs',
            name='hp_items',
        ),
        migrations.AddField(
            model_name='atributs',
            name='hp_koeficient',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Koeficient k životům'),
        ),
    ]
