# Generated by Django 5.1.5 on 2025-09-08 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0026_remove_atributs_hp_items_atributs_hp_koeficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='poz',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eqp',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='povolani',
            field=models.CharField(blank=True, choices=[('ranger', 'Hraničář'), ('paladin', 'Paladin'), ('mage', 'Mág')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, choices=[('human', 'Člověk'), ('elf', 'Elf'), ('dwarf', 'Trpaslík'), ('ork', 'Ork'), ('gnóm', 'Gnóm'), ('shadow', 'Stín')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20),
        ),
    ]
