# Generated by Django 5.1.5 on 2025-09-08 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0027_remove_playerinfo_poz_playerinfo_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqp',
            name='item_base_damage',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_level_required',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_level_stop',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_max_damage',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_min_damage',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_slots',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='item_weapon_type',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_base_damage',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_level_required',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_level_stop',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_max_damage',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_min_damage',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_slots',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='item_weapon_type',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_base_damage',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_level_required',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_level_stop',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_max_damage',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_min_damage',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_slots',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='item_weapon_type',
        ),
        migrations.AddField(
            model_name='eqp',
            name='armor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='dex_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='img_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='int_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='item_category',
            field=models.CharField(choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='eqp',
            name='level_required',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='level_stop',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='luk_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='max_dmg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='min_dmg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eqp',
            name='prum_dmg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_1_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_1_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_2_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_2_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_3_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_3_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_4_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slot_4_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='str_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eqp',
            name='vit_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='armor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='dex_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='img_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='int_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='item_category',
            field=models.CharField(choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='inv',
            name='level_required',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='level_stop',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='luk_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='max_dmg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='min_dmg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inv',
            name='prum_dmg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_1_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_1_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_2_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_2_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_3_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_3_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_4_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slot_4_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='str_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='vit_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='armor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='dex_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='img_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='int_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='item_category',
            field=models.CharField(choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='level_required',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='level_stop',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='luk_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='max_dmg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='min_dmg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='prum_dmg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_1_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_1_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_2_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_2_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_3_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_3_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_4_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slot_4_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='str_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='vit_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eqp',
            name='hrac',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eqp',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eqp',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_offer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
    ]
