# Generated by Django 5.1.5 on 2025-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0028_remove_eqp_item_base_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp',
            name='item_type',
            field=models.CharField(blank=True, choices=[('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_type',
            field=models.CharField(blank=True, choices=[('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='item_type',
            field=models.CharField(blank=True, choices=[('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_type',
            field=models.CharField(blank=True, choices=[('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
    ]
