# Generated by Django 5.1.5 on 2025-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0029_alter_eqp_item_type_alter_inv_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp',
            name='item_category',
            field=models.CharField(blank=True, choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_category',
            field=models.CharField(blank=True, choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_category',
            field=models.CharField(blank=True, choices=[('weapon', 'zbraň'), ('armor', 'brnění'), ('helmet', 'helma'), ('boots', 'boty'), ('ring', 'prsten'), ('amulet', 'náhrdelník'), ('talisman', 'talisman')], max_length=20, null=True),
        ),
    ]
