# Generated by Django 5.1.5 on 2025-09-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0030_alter_eqp_item_category_alter_inv_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp',
            name='item_id',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_id',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_id',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Item ID'),
        ),
    ]
