# Generated by Django 5.1.5 on 2025-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0031_alter_eqp_item_id_alter_inv_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
