# Generated by Django 5.1.5 on 2025-09-10 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0032_alter_eqp_item_id_alter_inv_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp',
            name='hrac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqp', to=settings.AUTH_USER_MODEL),
        ),
    ]
