# Generated by Django 5.1.5 on 2025-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0034_alter_eqp_item_category_alter_inv_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoffer',
            name='pozn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
