# Generated by Django 5.1.5 on 2025-09-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0035_shopoffer_pozn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopoffer',
            name='pozn',
        ),
    ]
