# Generated by Django 5.1.5 on 2025-09-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0036_remove_shopoffer_pozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_bonus',
            name='hrac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_bonus', to=settings.AUTH_USER_MODEL),
        ),
    ]
