# Generated by Django 5.1.5 on 2025-09-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0037_alter_character_bonus_hrac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqp',
            name='slot_1_bonus',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_1_value',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_2_bonus',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_2_value',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_3_bonus',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_3_value',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_4_bonus',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slot_4_value',
        ),
        migrations.RemoveField(
            model_name='eqp',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_1_bonus',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_1_value',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_2_bonus',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_2_value',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_3_bonus',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_3_value',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_4_bonus',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slot_4_value',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_1_bonus',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_1_value',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_2_bonus',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_2_value',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_3_bonus',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_3_value',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_4_bonus',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slot_4_value',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='slots',
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='bezvedomi_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='dex_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k obratnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='heavy_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti těžkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='hp_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='int_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k inteligenci (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='kriticke_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus ke kritickému poškození (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='light_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti lehkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='luck_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus ke zručnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='magic_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti magii (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='otrava_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti otravě (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='poskozeni_schopnosti_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození ze schopností (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='poskozeni_utokem_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození z útoku (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='pvm_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='pvm_resist_procent_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='pvp_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='pvp_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='sance_na_bezvedomi_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='sance_na_otravu_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na otravu (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='str_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k síle (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='vit_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k vitalitě (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='bezvedomi_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='dex_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k obratnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='heavy_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti těžkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='hp_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='int_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k inteligenci (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='kriticke_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus ke kritickému poškození (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='light_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti lehkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='luck_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus ke zručnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='magic_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti magii (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='otrava_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti otravě (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='poskozeni_schopnosti_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození ze schopností (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='poskozeni_utokem_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození z útoku (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='pvm_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='pvm_resist_procent_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='pvp_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='pvp_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='sance_na_bezvedomi_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='sance_na_otravu_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na otravu (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='str_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k síle (předměty)'),
        ),
        migrations.AddField(
            model_name='eqp',
            name='vit_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k vitalitě (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='bezvedomi_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='dex_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k obratnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='heavy_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti těžkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='hp_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='int_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k inteligenci (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='kriticke_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus ke kritickému poškození (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='light_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti lehkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='luck_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus ke zručnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='magic_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti magii (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='otrava_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti otravě (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='poskozeni_schopnosti_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození ze schopností (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='poskozeni_utokem_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození z útoku (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='pvm_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='pvm_resist_procent_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='pvp_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='pvp_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='sance_na_bezvedomi_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='sance_na_otravu_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na otravu (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='str_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k síle (předměty)'),
        ),
        migrations.AddField(
            model_name='inv',
            name='vit_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k vitalitě (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='bezvedomi_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='dex_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k obratnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='heavy_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti těžkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='hp_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='int_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k inteligenci (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='kriticke_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus ke kritickému poškození (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='light_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti lehkým zbraním (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='luck_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus ke zručnosti (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='magic_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti magii (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='otrava_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti otravě (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='poskozeni_schopnosti_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození ze schopností (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='poskozeni_utokem_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození z útoku (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='pvm_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='pvm_resist_procent_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVM (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='pvp_poskozeni_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální bonus k poškození proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='pvp_resist_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální odolnost proti PVP (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='sance_na_bezvedomi_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na bezvědomí (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='sance_na_otravu_procenta_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Procentuální šance na otravu (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='str_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k síle (předměty)'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='vit_flat_it_bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k vitalitě (předměty)'),
        ),
    ]
