# Generated by Django 5.1.5 on 2025-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0038_remove_eqp_slot_1_bonus_remove_eqp_slot_1_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqp',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inv',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
