# Generated by Django 5.1.5 on 2025-09-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0039_eqp_slots_inv_slots_shopoffer_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eqp',
            old_name='pvm_resist_procent_it_bonus',
            new_name='pvm_resist_procenta_it_bonus',
        ),
        migrations.RenameField(
            model_name='inv',
            old_name='pvm_resist_procent_it_bonus',
            new_name='pvm_resist_procenta_it_bonus',
        ),
        migrations.RenameField(
            model_name='shopoffer',
            old_name='pvm_resist_procent_it_bonus',
            new_name='pvm_resist_procenta_it_bonus',
        ),
    ]
