# Generated by Django 5.1.5 on 2025-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0040_rename_pvm_resist_procent_it_bonus_eqp_pvm_resist_procenta_it_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='item_type',
            field=models.CharField(blank=True, choices=[('universal', 'Univerzální'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], max_length=20, null=True),
        ),
    ]
