# Generated by Django 5.1.5 on 2025-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0041_alter_eqp_item_type_alter_inv_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqp',
            name='sell_price',
            field=models.FloatField(default=0, verbose_name='Prodejní cena'),
        ),
        migrations.AddField(
            model_name='inv',
            name='sell_price',
            field=models.FloatField(default=0, verbose_name='Prodejní cena'),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='sell_price',
            field=models.FloatField(default=0, verbose_name='Prodejní cena'),
        ),
    ]
