# Generated by Django 5.1.5 on 2025-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0042_eqp_sell_price_inv_sell_price_shopoffer_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributs',
            name='charisma_base',
        ),
        migrations.RemoveField(
            model_name='atributs',
            name='charisma_cena',
        ),
        migrations.RemoveField(
            model_name='atributs',
            name='charisma_items',
        ),
        migrations.RemoveField(
            model_name='atributs',
            name='charisma_plus',
        ),
        migrations.RemoveField(
            model_name='atributs',
            name='suma_charisma',
        ),
        migrations.AddField(
            model_name='atributs',
            name='hp_items',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus k životům (předměty)'),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='dmg_atribut',
            field=models.CharField(blank=True, choices=[('strength', 'Síla'), ('dexterity', 'Obratnost'), ('intelligence', 'Inteligence'), ('luck', 'Štěstí'), ('vitality', 'Vitalita')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='luck_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní štěstí'),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='luck_cena',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena za zvýšení štěstí'),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='luck_items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k štěstí (předměty)'),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='luck_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k štěstí'),
        ),
    ]
