# Generated by Django 5.1.5 on 2025-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0043_remove_atributs_charisma_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_bonus',
            name='dex_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k obratnosti'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='int_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k inteligenci'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='luk_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus ke zručnosti'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='str_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k síle'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='vit_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bonus k vitalitě'),
        ),
    ]
