# Generated by Django 5.1.5 on 2025-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0044_character_bonus_dex_bonus_character_bonus_int_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_bonus',
            name='armor_suma',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Celková hodnota brnění (předměty)'),
        ),
    ]
