# Generated by Django 5.1.5 on 2025-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0045_character_bonus_armor_suma'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_bonus',
            name='armor_armor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hodnota brnění (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='armor_boots',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hodnota bot (předměty)'),
        ),
        migrations.AddField(
            model_name='character_bonus',
            name='armor_helmet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hodnota helmy (předměty)'),
        ),
    ]
