# Generated by Django 5.1.5 on 2025-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0046_character_bonus_armor_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_bonus',
            name='pozn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka k bonusu (pro mě)'),
        ),
    ]
