# Generated by Django 5.1.5 on 2025-09-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0047_character_bonus_pozn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_bonus',
            name='pozn',
        ),
    ]
