# Generated by Django 5.1.5 on 2025-09-24 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0048_remove_character_bonus_pozn'),
        ('pvmapp', '0002_alter_mobs_armor_alter_mobs_bezvedomi_resist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_id', models.UUIDField()),
                ('round_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('player_hp_before', models.IntegerField(blank=True, null=True)),
                ('player_hp_after', models.IntegerField(blank=True, null=True)),
                ('mob_hp_before', models.IntegerField(blank=True, null=True)),
                ('mob_hp_after', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=50)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvmapp.mobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
