# Generated by Django 5.1.5 on 2025-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0049_fightlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightlogentry',
            name='pozn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
