# Generated by Django 5.1.5 on 2025-09-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0050_fightlogentry_pozn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightlogentry',
            name='pozn',
        ),
    ]
