# Generated by Django 5.1.5 on 2025-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0051_remove_fightlogentry_pozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightlogentry',
            name='round_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
