# Generated by Django 5.1.5 on 2025-09-24 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0052_alter_fightlogentry_round_number'),
        ('pvmapp', '0002_alter_mobs_armor_alter_mobs_bezvedomi_resist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightlogentry',
            name='fight_id',
        ),
        migrations.RemoveField(
            model_name='fightlogentry',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='fightlogentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fightlogentry',
            name='winner',
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('fight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvmapp.mobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fightlogentry',
            name='fight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hracapp.fight'),
            preserve_default=False,
        ),
    ]
