# Generated by Django 5.1.5 on 2025-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0053_remove_fightlogentry_fight_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightlogentry',
            name='pozn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
