# Generated by Django 5.1.5 on 2025-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0055_remove_fightlogentry_pozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='mob',
            field=models.CharField(blank=True, default='Neznámý nepřítel', max_length=100, null=True),
        ),
    ]
