# Generated by Django 5.1.5 on 2025-09-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0056_alter_fight_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightlogentry',
            name='attack_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fightlogentry',
            name='attack_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fightlogentry',
            name='attack_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Útočná hodnota'),
        ),
        migrations.AddField(
            model_name='fightlogentry',
            name='defence_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Obranná hodnota'),
        ),
        migrations.AddField(
            model_name='fightlogentry',
            name='dmg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fightlogentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fightlogentry',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
