# Generated by Django 5.1.5 on 2025-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0057_fightlogentry_attack_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightlogentry',
            name='base_armor',
            field=models.FloatField(blank=True, null=True, verbose_name='Základní obrana'),
        ),
    ]
