# Generated by Django 5.1.5 on 2025-09-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0058_fightlogentry_base_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightlogentry',
            name='minus_hp_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Procentuální snížení HP'),
        ),
    ]
