# Generated by Django 5.1.5 on 2025-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0059_fightlogentry_minus_hp_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqp',
            name='img_init',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='img_init',
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='img_init',
        ),
        migrations.AddField(
            model_name='eqp',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inv',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
