# Generated by Django 5.1.5 on 2025-10-01 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0060_remove_eqp_img_init_remove_inv_img_init_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('id_of_mobs_cleared', models.IntegerField(blank=True, default=0, null=True, verbose_name='Poražené dungeon mobky')),
                ('hrac', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
