# Generated by Django 5.1.5 on 2025-10-01 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0061_dungeon_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon_progress',
            name='get_gold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Získané GOLDY'),
        ),
        migrations.AddField(
            model_name='dungeon_progress',
            name='get_xp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Získané XP'),
        ),
        migrations.AlterField(
            model_name='dungeon_progress',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
